# --- PLEASE EDIT THE LINES BELOW CORRECTLY ---
# SOME DESCRIPTIVE TITLE.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2024-01-22 13:23+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI +ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0\n"
"Language-Code: en\n"
"Language-Name: English\n"
"Preferred-Encodings: utf-8 latin1\n"
"Domain: tud.addons.deepl\n"

#: ./adapter/deepl_api.py:55
msgid "Authentication token was not accepted"
msgstr ""

#: ./adapter/deepl_api.py:52
msgid "Can not connect to DeepL API URL"
msgstr ""

#: ./adapter/deepl_api.py:65
msgid "DeepL API request returns with an error. Server response:"
msgstr ""

#: ./adapter/deepl_api.py:60
msgid "DeepL translation quota exeeded"
msgstr ""

#: ./configure.zcml:35
msgid "Installs the tud.addons.deepl add-on."
msgstr ""

#: ./testing.zcml:14
msgid "Steps for tud.addons.deepl tests"
msgstr ""

#: ./adapter/deepl_api.py:57
msgid "Too many concurrent requests to DeepL"
msgstr ""

#: ./configure.zcml:44
msgid "Uninstalls the tud.addons.deepl add-on."
msgstr ""

#. Default: "Authentication key for the DeepL API"
#: ./interfaces.py:35
msgid "deepl_api_auth_token"
msgstr ""

#. Default: "ID of the glossary"
#: ./interfaces.py:41
msgid "deepl_api_glossary_id"
msgstr ""

#. Default: "Connect/Read timeout for the remote connection to the DeepL API"
#: ./interfaces.py:28
msgid "deepl_api_timeout"
msgstr ""

#. Default: "Time in seconds; should be between 3 and 10"
#: ./interfaces.py:29
msgid "deepl_api_timeout_desc"
msgstr ""

#. Default: "URL of DeepL API without endpoint"
#: ./interfaces.py:22
msgid "deepl_api_url"
msgstr ""

#: ./configure.zcml:35
msgid "tud.addons.deepl"
msgstr ""

#: ./configure.zcml:44
msgid "tud.addons.deepl (uninstall)"
msgstr ""

#: ./testing.zcml:14
msgid "tud.addons.deepl tests"
msgstr ""
